<a href="https://colab.research.google.com/github/Abu-Musa38/colab/blob/main/GridSearchCV_and_RandomizedSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hyperparameter Tuning:
GridSearchCV

RandomizedSearchCV

In [3]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

We will be working on the breast cancer dataset

In [4]:
breast_cancer_dataset=sklearn.datasets.load_breast_cancer()

In [5]:
print(breast_cancer_dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [6]:
data_frame=pd.DataFrame(breast_cancer_dataset.data,columns=breast_cancer_dataset.feature_names)

In [7]:
data_frame.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [8]:
# adding the 'target' column to the data frame
data_frame['label'] = breast_cancer_dataset.target

In [9]:
data_frame.head()

mean radius  mean texture  ...  worst fractal dimension  label
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [10]:
data_frame.shape

(569, 31)

In [11]:
data_frame.isnull().sum()


mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [12]:
# checking the distribution of Target Varibale
data_frame['label'].value_counts()

label
1    357
0    212
Name: count, dtype: int64

1 --> Benign

0 --> Malignant

In [13]:
X = data_frame.drop(columns='label', axis=1)
Y = data_frame['label']

In [14]:
print(X)

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]


In [15]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: label, Length: 569, dtype: int64


In [17]:
 X = np.asarray(X)
 Y = np.asarray(Y)

In [18]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [19]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

# **GridSearchCV**

In [20]:
# loading the SVC model
model = SVC()

In [21]:

# hyperparameters

parameters = {
              'kernel':['linear','poly','rbf','sigmoid'],
              'C':[1, 5, 10, 20]
}


In [22]:
# grid search
classifier = GridSearchCV(model, parameters, cv=5)

In [23]:
# fitting the data to our model
classifier.fit(X, Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [24]:
classifier.cv_results_

{'mean_fit_time': array([1.66720662e+00, 4.05116081e-03, 5.12461662e-03, 1.51085854e-02,
        3.49933043e+00, 4.00567055e-03, 4.35318947e-03, 1.38612747e-02,
        4.69676709e+00, 4.20756340e-03, 4.30335999e-03, 1.49099350e-02,
        7.80807290e+00, 4.69956398e-03, 4.39701080e-03, 1.59557819e-02]),
 'std_fit_time': array([7.32471323e-01, 1.39729756e-04, 2.25802680e-04, 4.20066690e-04,
        9.46854134e-01, 2.84474710e-04, 1.40283239e-04, 5.20383330e-04,
        9.29424601e-01, 1.83199347e-04, 2.18857586e-04, 1.25328901e-03,
        2.69600161e+00, 8.63933137e-05, 1.37554305e-04, 3.22556410e-03]),
 'mean_score_time': array([0.00172625, 0.00160942, 0.00307741, 0.00475817, 0.00218925,
        0.00150251, 0.00192876, 0.00386453, 0.00169096, 0.00138226,
        0.00180144, 0.00415096, 0.00149307, 0.00152693, 0.0018137 ,
        0.00487943]),
 'std_score_time': array([2.40393593e-04, 6.38893465e-05, 1.56394022e-03, 8.69957887e-04,
        1.17970832e-03, 6.69317008e-05, 9.83500654e-

In [25]:
# best parameters

best_parameters = classifier.best_params_
print(best_parameters)

{'C': 10, 'kernel': 'linear'}


In [26]:
# higest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.9525694767893185


In [27]:
# loading the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)

In [28]:
result.head()

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       1.667207      0.732471  ...        0.018689                4
1       0.004051      0.000140  ...        0.039382               12
2       0.005125      0.000226  ...        0.035444               11
3       0.015109      0.000420  ...        0.050253               13
4       3.499330      0.946854  ...        0.016216                2

[5 rows x 15 columns]

In [29]:
grid_search_result = result[['param_C','param_kernel','mean_test_score']]

In [30]:
grid_search_result

param_C param_kernel  mean_test_score
0         1       linear         0.945536
1         1         poly         0.908663
2         1          rbf         0.912172
3         1      sigmoid         0.460441
4         5       linear         0.950815
5         5         poly         0.922729
6         5          rbf         0.931501
7         5      sigmoid         0.411178
8        10       linear         0.952569
9        10         poly         0.920975
10       10          rbf         0.922714
11       10      sigmoid         0.402391
12       20       linear         0.949061
13       20         poly         0.919221
14       20          rbf         0.920944
15       20      sigmoid         0.398867

Highest Accuracy = 95.2%

Best Parameters = {'C':10, 'kernel':'linear'}

# **RandomizedSearchCV**

In [35]:
# loading the SVC model
model = SVC()

In [37]:
# hyperparameters

parameters = {
              'kernel':['linear','poly','rbf','sigmoid'],
              'C':[1, 5, 10, 20]
}

In [33]:
# grid search
classifier = RandomizedSearchCV(model, parameters, cv=5)

In [34]:
# fitting the data to our model
classifier.fit(X, Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [39]:
classifier.cv_results_

{'mean_fit_time': array([4.97465134e-03, 1.74941063e-02, 7.86571169e+00, 3.18285222e+00,
        3.75013351e-03, 1.52100086e-02, 1.37221336e-02, 4.39858437e-03,
        1.62742314e+00, 1.35755062e-02]),
 'std_fit_time': array([2.75230325e-04, 3.78602604e-03, 2.00460407e+00, 8.55227921e-01,
        7.14744385e-05, 1.09568775e-03, 4.96551975e-04, 1.12491434e-04,
        5.35210850e-01, 5.77539024e-04]),
 'mean_score_time': array([0.0022161 , 0.00527301, 0.0015831 , 0.00178084, 0.00147095,
        0.00429468, 0.00363793, 0.00136027, 0.0016243 , 0.00385618]),
 'std_score_time': array([8.99652850e-05, 1.51504285e-03, 1.99031910e-04, 5.09990072e-04,
        1.56156707e-05, 3.02974368e-04, 8.20942162e-05, 4.23753998e-05,
        1.65063806e-04, 2.87626696e-04]),
 'param_kernel': masked_array(data=['rbf', 'sigmoid', 'linear', 'linear', 'poly',
                    'sigmoid', 'sigmoid', 'poly', 'linear', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
    

In [38]:
# best parameters

best_parameters = classifier.best_params_
print(best_parameters)

{'kernel': 'linear', 'C': 5}


In [40]:
# higest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.9508150908244062


In [41]:
# loading the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)

In [42]:
result.head()

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.004975      0.000275  ...        0.035444                5
1       0.017494      0.003786  ...        0.048578                8
2       7.865712      2.004604  ...        0.012816                2
3       3.182852      0.855228  ...        0.016216                1
4       0.003750      0.000071  ...        0.039382                6

[5 rows x 15 columns]

In [43]:
randomized_search_result = result[['param_C','param_kernel','mean_test_score']]

In [44]:
randomized_search_result

param_C param_kernel  mean_test_score
0        1          rbf         0.912172
1        5      sigmoid         0.411178
2       20       linear         0.949061
3        5       linear         0.950815
4        1         poly         0.908663
5        1      sigmoid         0.460441
6       10      sigmoid         0.402391
7       20         poly         0.919221
8        1       linear         0.945536
9       20      sigmoid         0.398867

Highest Accuracy = 95.2%

Best Parameters = {'C':10, 'kernel':'linear'}